### ISSUE TITLE
Cannot Find Device.html

### ISSUE THREAD

**Issue by GerryGit** [futuretechguy/ESP_WeatherStation#1]
I am trying to build this code in PlatformIO, with some success. However I am expecting to find a device.html file somewhere which would be uploaded to spiffs. Not sure if I am reading this correctly, but it does not seem to be included. Thanks for assistance.

**Comment by futuretechguy** [comment]
Hi GerryGit,

I provided a link to the library below, however it won't help if you don't have Homeseer running on you network. You can comment out any reference to the library. Please let me know if you have more questions or require any assistance.

https://github.com/futuretechguy/HomeseerSend/tree/master

**Comment by futuretechguy** [comment]
Hi GGerryGir,

Sorry I did not take the time to read correctly.  
PlatformIO works a little different from the Arduino IDE, you can create the device.html file using the details in the devicecontrol.h file starting from the HTML tag

**Comment by futuretechguy** [comment]
Sorry I used the Arduino IDE which works a little different from PlatformIO. You can use the details in the devicecontrol.h to create the device.html file starting from the HTML tag.
